#!/bin/bash

curl -s http://ifconfig.co/json | jq . > json.out

messyIP=$(jq .ip json.out)
messycountry=$(jq .country json.out)
messyregion=$(jq .region_name json.out)

IP=$(eval echo $messyIP)
country=$(eval echo $messycountry)
region=$(eval echo $messyregion)


echo $IP
echo $country
echo $region