#!/bin/bash

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
#                                                         #
#                 Public IP Log Script                    #
#                                                         #
#     This script pulls the current public IP of the      #
#      machine from ifconfig.co and creates a simple      #
#    HTML page in the folder "/var/www/html/current-ip"   #
#     which displays the current public IP, Country and   #
#   Region of the IP.  It also keeps a log of the         #
#      results each time the script is run and saves it   #
#     in log.txt also in the "/var/www/html/current-ip"   #
#     folder.                                             #
#                                                         #
#      This script depends on a webserver installed       #
#    with it's root path set to "/var/www/html".  It      #
#     also depends on jq being installed to parse         #
#      JSON files.                                        #
#                                                         #
#              Written by:  Tyler M Johnson               #
#           https://github.com/yippieskippie24            #
#     https://github.com/yippieskippie24/Public-IP-log    #
#                                                         #
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
#     Define all variables used in this script            #
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

date=$(date)
messyIP=""
IP=""
messycountry=""
country=""
messyregion=""
region=""

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# Get public IP info and save it as '/tmp/current-ip.json'#
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

curl -s http://ifconfig.co/json | jq . > /tmp/current-ip.json

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
#    Clean up output and save it as useable variables     #
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

messyIP=$(jq .ip /tmp/current-ip.json)
messycountry=$(jq .country /tmp/current-ip.json)
messyregion=$(jq .region_name /tmp/current-ip.json)

IP=$(eval echo $messyIP)
country=$(eval echo $messycountry)
region=$(eval echo $messyregion)


#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
#          Delete existing index.html file                #
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

touch /var/www/html/current-ip/index.html
rm /var/www/html/current-ip/index.html

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# Build new index.html file based on collected variables  #
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

cat > /var/www/html/current-ip/index.html << EOF

<!DOCTYPE html>
<html>
<body>
<h1>Current Public IP</h1>
<h1>$IP</h1>
<br>
Country: $country
<br>
Region: $region
<br>
$date
<br>
<p><a href=log.txt>View Logs</a></p>
</body>
</html>
EOF

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
#                 Prepend to log file                     #
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

cp /var/www/html/current-ip/log.txt /var/www/html/current-ip/log.txt.bak
touch /var/www/html/current-ip/log.txt
rm /var/www/html/current-ip/log.txt
echo "$date | $country | $region | $IP" >> /var/www/html/current-ip/log.txt
cat /var/www/html/current-ip/log.txt.bak >> /var/www/html/current-ip/log.txt

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#