#!/bin/bash


rm /var/www/html/index.html
cp /var/www/html/log.txt /var/www/html/log.txt.bak
json=$(curl -s http://ifconfig.co/json | jq .)

date=$(date)
IP=$(curl -s ifconfig.co/ip)
country=$(curl -s ifconfig.co/country)

echo "<!DOCTYPE html>" >> /var/www/html/index.html
echo "<html>" >> /var/www/html/index.html
echo "<body>" >> /var/www/html/index.html
echo "<h1>Current Public IP</h1>" >> /var/www/html/index.html
echo "<h1>$IP</h1>" >> /var/www/html/index.html
echo "<br>" >> /var/www/html/index.html
echo "Country: $country" >> /var/www/html/index.html
echo "<br>" >> /var/www/html/index.html
echo "$date" >> /var/www/html/index.html
echo "<br>" >> /var/www/html/index.html
echo "<p><a href="http://10.0.200.202/log.txt">View Logs</a></p>" >> /var/www/html/index.html
echo "</body>" >> /var/www/html/index.html
echo "</html>" >> /var/www/html/index.html


rm /var/www/html/log.txt
echo "$date | $country | $IP" >> /var/www/html/log.txt
cat /var/www/html/log.txt.bak >> /var/www/html/log.txt
